"""empty message

Revision ID: 35b0246f0fb6
Revises: e71d2d205e38
Create Date: 2020-12-24 16:53:16.126094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b0246f0fb6'
down_revision = 'e71d2d205e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
